title: Blowing Minds
author: GitHub User
email: isra.neri2@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Everything can happens nothing is impossible.
theme: minima
# social links
twitter_username: jimibilibob # DO NOT include the @ character, or else the build will fail!
github_username:  jimibilibob # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
